// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlpARBKw0SJRLofBBCuPYHahUAh3yqCDQ',
    appId: '1:260428267973:web:a2f796055467f343eb0bac',
    messagingSenderId: '260428267973',
    projectId: 'kynex-e740b',
    authDomain: 'kynex-e740b.firebaseapp.com',
    storageBucket: 'kynex-e740b.firebasestorage.app',
    measurementId: 'G-41RF5DMN3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4-PtYEKeVY6UnbzpJPzCFD9lCn7jXT0',
    appId: '1:260428267973:android:00c4c3c2d9b3fa8aeb0bac',
    messagingSenderId: '260428267973',
    projectId: 'kynex-e740b',
    storageBucket: 'kynex-e740b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdCCEtb7bq1lZ4YEi4IpQSgaRqN0W2Zo',
    appId: '1:260428267973:ios:d0d99459d7ac323beb0bac',
    messagingSenderId: '260428267973',
    projectId: 'kynex-e740b',
    storageBucket: 'kynex-e740b.firebasestorage.app',
    iosBundleId: 'com.example.kynex',
  );
}
